services:

  api:
    build: .
    container_name: api_pfc
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      SENDGRID_API_KEY: /run/secrets/sendgrid_api_key
      SENDGRIP_MAIL: /run/secrets/sendgrid_mail
      USE_DOCKER_SECRETS: true
    secrets:
      - db_password
      - db_user
      - jwt_secret
      - sendgrid_api_key
      - sendgrid_mail
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db_pfc
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    secrets:
      - db_password
      - db_user

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  sendgrid_api_key:
    file: ./secrets/sendgrid_api_key.txt
  sendgrid_mail:
    file: ./secrets/sendgrid_mail.txt

